### ISSUE TITLE
Moo over Moose

### ISSUE THREAD

**Issue by tehmoth** [shantanubhadoria/perl-Printer-ESCPOS#1]
have you considered using the lighter weight Moo / Moo::Role / Type::Tiny over Moose / Moose::Role / TypeConstraints?

**Comment by shantanubhadoria** [comment]
I haven't thought about it yet, Its a good idea but I do need some subclassing and advanced functionality, so I must check if everything works. But thanks for the suggestion, I will look into it. I will keep this issue open for now.
Cheers!

**Comment by shantanubhadoria** [comment]
Looks like it works fine with Moo. I had to get rid for some type validation for some params but its probably better to implement those checks at the user level.
